# Use the official NGINX image as the base image
FROM nginx:alpine

# Remove default NGINX configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy the content of the "dist" directory to the NGINX web server root
COPY frontend/dist /usr/share/nginx/html

# Copy the custom NGINX configuration for SPA routing
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start the NGINX web server
CMD ["nginx", "-g", "daemon off;"]
