# Use the official NGINX image as the base image
FROM node:18-alpine

# Expose port 4173
EXPOSE 4173

# Build app
WORKDIR /app
COPY frontend/ /app
RUN yarn install
RUN yarn build

# Start the NGINX web server
CMD ["yarn", "preview", "--host"]
