name: student-attendance-chatbot
version: "1.0.0"
services:
  api:
    build:
      dockerfile: ./dockerfile
    container_name: chatbot-api
    environment:
      HOST: api
      PORT: 3001
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - 3001:3001
  web:
    build:
      dockerfile: ./frontend/dockerfile
    container_name: chatbot-frontend
    ports:
      - 8080:80
