# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json ./

# Install any needed packages specified in package.json
RUN yarn install

# Copy all local files to the image's working directory
COPY . .

# Make port 3000 available to the world outside this container
EXPOSE 3001

# Define environment variable
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3001

# Run npm start when the container launches
CMD ["yarn", "dev"]
